site_name: Zsh 中文手册
site_author: '雨宫恋叶'
site_url: 'https://shadowrz.github.io/zshdocs-zh/'
docs_dir: 'content'
repo_url: https://github.com/ShadowRZ/zshdocs-zh
repo_name: 'ShadowRZ/zshdocs-zh'
copyright: '2020 雨宫恋叶'
theme:
    language: 'zh'
    name: 'material'
    palette:
        primary: 'purple'
        accent: 'light green'
    logo:
        icon: 'code'
plugins:
    - search
    - git-revision-date-localized:
        type: iso_datetime
    - minify:
        minify_html: true
markdown_extensions:
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
    - admonition
    - footnotes
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.escapeall
    - markdown.extensions.def_list
